name: Build and Release Powerlang

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev portaudio19-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller using spec file
        run: pyinstaller Powerlang.spec
        
      - name: Prepare Release Artifacts
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ARTIFACT_NAME="Powerlang-Windows.zip"
            cd dist
            7z a ../${ARTIFACT_NAME} ./Powerlang.exe
            cd ..
          else
            ARTIFACT_NAME="Powerlang-Linux.tar.gz"
            cd dist
            tar -czvf ../${ARTIFACT_NAME} Powerlang
            cd ..
          fi
          echo "ASSET_PATH=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}